### ISSUE TITLE
3D Points

### ISSUE THREAD

**Issue by sctrueew** [iwatake2222/opencv_sample#2]
@iwatake2222 Hi,

Thanks for sharing. I have some questions about the reconstruction. 

1. Can we use MIDAS V3?
2. How can I save 3D Points and display them on another viewer?
3. How can I measure?

**Comment by iwatake2222** [comment]
> Can we use MIDAS V3?

I'm not familiar with MiDaS v3, but any depth estimation model can be used by modifying https://github.com/iwatake2222/opencv_sample/blob/master/reconstruction_depth_to_3d/depth_engine.cpp

> How can I save 3D Points and display them on another viewer?

3D points are stored in `object_point_list` variable. Just write code to save it in a format you want.
(I don't know about another viewer)

**Comment by sctrueew** [comment]
@iwatake2222 Hi,

I added a mothod to the common.h file and I want to measure distance between points, but I get wrong result.

```
float distancePoint3d(cv::Point3f& object_point1, cv::Point3f& object_point2)
    {
        float d = sqrt(pow(object_point2.x - object_point1.x, 2) +
            pow(object_point2.y - object_point1.y, 2) +
            pow(object_point2.z - object_point1.z, 2) * 1.0);
        return d;
    }
```

**Comment by sctrueew** [comment]
@iwatake2222 Hi,

Can I use 3D reconstruction instead of Lidar? I mean I have a video like the KITTI dataset that I'd like to generate 3D points cloud from sequential frames. for example:

![image](https://user-images.githubusercontent.com/5433346/145557056-1ab43f4e-4bd0-452c-b486-e627e3dc372e.png)

The top figure shows the 3D surface reconstruction over 250 frames. but my result isn't like that.

I've saved about 20 frame points data every 30 fps and the distance between each frame is almost 8(meter).

1. The beginning of each frame is long
![image](https://user-images.githubusercontent.com/5433346/145559348-89617c3d-d1d8-41bb-b7dd-713582a309f0.png)

2. All points overlap.
![image](https://user-images.githubusercontent.com/5433346/145560178-68be8615-bd3b-42c4-a6ea-4249b569ac56.png)

Should I use SLAM for making a scene?

Thanks in advance

**Comment by iwatake2222** [comment]
My project just generates point cloud from a single still image, so I don't think it can be used for your purpose.
By the way, this repo is just for my experiment and it's not so practical for the real project. I suggest using Open3D or PCL.

**Comment by sctrueew** [comment]
@iwatake2222 Hi,

Thanks for the reply, I've searched about Open3D and need RGBD data to generate reconstruction points cloud. unfortunately, I'm not very familiar with Open3D and I don't have an RGBD camera to use it and I'd like to use depth estimation like this sample to make an RGBD frame and then generate a point cloud. Do you think this can be done?

Thanks

**Comment by iwatake2222** [comment]
Maybe yes.

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
